# Generated by Django 5.1.2 on 2024-10-22 17:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название аренды')),
                ('clientname', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('image', models.CharField(max_length=500, verbose_name='URL-фото')),
                ('salary', models.CharField(max_length=80, verbose_name='Цена')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефоне')),
                ('insta', models.CharField(max_length=30, verbose_name='Инстаграм')),
                ('like', models.CharField(max_length=30, verbose_name='Лайки')),
                ('view', models.CharField(max_length=30, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp_app.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
    ]
