# Generated by Django 5.1.2 on 2024-10-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_app', '0002_remove_rent_view_rent_vie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='vie',
            new_name='view',
        ),
    ]
