# Generated by Django 5.1.2 on 2024-10-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_app', '0003_rename_vie_rent_view'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rent',
            new_name='Job',
        ),
    ]
